name: GitHub Pages

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read
  pages: write
  id-token: write

env:
  BASE_URL: /${{ github.event.repository.name }}

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: false

      - name: Checkout submodules
        run: |
          git config --global url."https://x-access-token:${{ secrets.CLASSES_PAT }}@github.com/tatsy-classes/".insteadOf "https://github.com/tatsy-classes/"
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./_build/html/

  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Github Pages deployment
        id: deployment
        uses: actions/deploy-pages@v5
        if: github.ref == 'refs/heads/main'
